fix: unit test workflow: add debug

diff --git a/.github/workflows/test-paper-notebooks.yml b/.github/workflows/test-paper-notebooks.yml
--- a/.github/workflows/test-paper-notebooks.yml
+++ b/.github/workflows/test-paper-notebooks.yml
@@ -62,8 +62,10 @@ jobs:
             jupyter nbconvert --to pdf $notebook
           done
 
-          if [[ ! $error_flag -eq "0" ]]
+          echo "End of evaluation $error_flag"
+          if [[ "$error_flag" != "0" ]]
           then
+            echo "Trying to exit 1"
             exit 1
           fi
 
